apiVersion: pubsub.cnrm.cloud.google.com/v1alpha1
kind: PubSubSubscription
metadata:
  labels:
    label-one: "value-one"
  name: pubsubsubscription-sample
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: pubsubtopic-sample
