apiVersion: storage.cnrm.cloud.google.com/v1alpha1
kind: StorageBucket
metadata:
  labels:
    label-one: "value-one"
  name: storagebucket-sample
spec:
  lifecycle:
    rules:
      - action:
          type: Delete
        condition:
          age: 7
